import os
import sys
import types
import time
import asyncio
from datetime import datetime
from pathlib import Path

# Ensure numba shim for environments where numba C-extensions are not prebuilt
if "numba" not in sys.modules:
    try:
        import numba
    except ImportError:
        _numba = types.ModuleType("numba")
        _numba.njit = lambda *a, **k: (a[0] if (len(a) == 1 and callable(a[0])) else (lambda fn: fn))
        _numba.jit = _numba.njit
        _numba.prange = range
        sys.modules["numba"] = _numba

import pandas as pd
import pandas_ta as ta
from dotenv import load_dotenv
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.text import Text

# Try importing tvDatafeed and yfinance
try:
    from tvDatafeed import TvDatafeed, Interval
    TV_AVAILABLE = True
except Exception as e:
    TV_AVAILABLE = False

try:
    import yfinance as yf
    YF_AVAILABLE = True
except Exception as e:
    YF_AVAILABLE = False

# Load environment variables
load_dotenv()

console = Console()

# Configuration
ASSETS_ENV = os.getenv("ASSETS", "EURUSD,GBPUSD")
ASSET_LIST = [s.strip().upper() for s in ASSETS_ENV.split(",") if s.strip()]
CANDLE_COUNT = int(os.getenv("CANDLE_COUNT", "250"))
EMA_PERIOD = int(os.getenv("EMA_PERIOD", "200"))
RSI_PERIOD = int(os.getenv("RSI_PERIOD", "14"))
RSI_OVERSOLD = float(os.getenv("RSI_OVERSOLD", "30.0"))
RSI_OVERBOUGHT = float(os.getenv("RSI_OVERBOUGHT", "70.0"))
POLL_INTERVAL = int(os.getenv("POLL_INTERVAL", "10"))  # seconds between checks

# Initialize tvDatafeed instance (no login needed)
tv_client = None
if TV_AVAILABLE:
    try:
        tv_client = TvDatafeed()
    except Exception as e:
        console.print(f"[yellow]Warning: Could not initialize TvDatafeed: {e}[/yellow]")


def fetch_candles_tradingview(symbol: str, n_bars: int = CANDLE_COUNT) -> pd.DataFrame:
    """Fetches live 1-minute candle data from TradingView via tvDatafeed."""
    if not tv_client:
        return pd.DataFrame()

    # Try standard forex exchanges on TradingView
    exchanges = ["FX_IDC", "FX", "OANDA", "FOREXCOM", "SAXO"]
    for ex in exchanges:
        try:
            df = tv_client.get_hist(
                symbol=symbol,
                exchange=ex,
                interval=Interval.in_1_minute,
                n_bars=n_bars
            )
            if df is not None and not df.empty:
                df = df.reset_index()
                # Ensure datetime column is named 'time'
                if "datetime" in df.columns:
                    df["time"] = pd.to_datetime(df["datetime"])
                return df
        except Exception:
            continue

    return pd.DataFrame()


def fetch_candles_yfinance(symbol: str) -> pd.DataFrame:
    """Fallback: Fetches 1-minute candle data from Yahoo Finance."""
    if not YF_AVAILABLE:
        return pd.DataFrame()

    yf_symbol = f"{symbol}=X"
    try:
        df = yf.download(yf_symbol, period="1d", interval="1m", progress=False)
        if df is not None and not df.empty:
            # Flatten multi-index columns if generated by modern yfinance
            if isinstance(df.columns, pd.MultiIndex):
                df.columns = [col[0].lower() for col in df.columns]
            else:
                df.columns = [str(col).lower() for col in df.columns]

            df = df.reset_index()
            # Standardize datetime column
            if "datetime" in df.columns:
                df["time"] = pd.to_datetime(df["datetime"])
            elif "index" in df.columns:
                df["time"] = pd.to_datetime(df["index"])
            return df
    except Exception as e:
        console.print(f"[dim]yfinance error for {symbol}: {e}[/dim]")

    return pd.DataFrame()


def get_live_candles(symbol: str) -> tuple[pd.DataFrame, str]:
    """
    Attempts to retrieve 1-min candles from TradingView first, then yfinance.
    Returns (DataFrame, source_name).
    """
    # 1. Try TradingView
    df_tv = fetch_candles_tradingview(symbol, n_bars=CANDLE_COUNT)
    if not df_tv.empty and len(df_tv) >= 15:
        return df_tv, "TradingView"

    # 2. Try yfinance fallback
    df_yf = fetch_candles_yfinance(symbol)
    if not df_yf.empty and len(df_yf) >= 15:
        return df_yf, "Yahoo Finance"

    return pd.DataFrame(), "None"


def calculate_indicators(df: pd.DataFrame) -> pd.DataFrame:
    """
    Computes 200 EMA and 14 RSI on the candle DataFrame.
    """
    if df.empty or "close" not in df.columns:
        return df

    # Standardize column types and sort chronologically
    df["close"] = pd.to_numeric(df["close"], errors="coerce")
    df["open"] = pd.to_numeric(df["open"], errors="coerce")
    df["high"] = pd.to_numeric(df["high"], errors="coerce")
    df["low"] = pd.to_numeric(df["low"], errors="coerce")

    if "time" in df.columns:
        df["time"] = pd.to_datetime(df["time"], errors="coerce")
        df = df.sort_values(by="time").reset_index(drop=True)

    # 14 RSI calculation using pandas_ta (with native fallback)
    try:
        rsi_series = ta.rsi(df["close"], length=RSI_PERIOD)
        df[f"RSI_{RSI_PERIOD}"] = rsi_series
    except Exception:
        delta = df["close"].diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=RSI_PERIOD).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=RSI_PERIOD).mean()
        rs = gain / loss.replace(0, float("nan"))
        df[f"RSI_{RSI_PERIOD}"] = 100 - (100 / (1 + rs))

    # 200 EMA calculation using pandas_ta (with native fallback)
    try:
        ema_series = ta.ema(df["close"], length=min(EMA_PERIOD, len(df)))
        df[f"EMA_{EMA_PERIOD}"] = ema_series
    except Exception:
        df[f"EMA_{EMA_PERIOD}"] = df["close"].ewm(span=min(EMA_PERIOD, len(df)), adjust=False).mean()

    return df


def check_trading_signal(df: pd.DataFrame) -> tuple[str, str, float, float, float]:
    """
    Evaluates trading conditions based on 200 EMA and 14 RSI.
    
    Returns:
        tuple: (signal, reason, latest_close, latest_ema, latest_rsi)
    """
    if len(df) < 2:
        return "NEUTRAL", "Insufficient candle data", 0.0, 0.0, 0.0

    latest = df.iloc[-1]
    prev = df.iloc[-2]

    close = float(latest["close"])
    ema = float(latest[f"EMA_{EMA_PERIOD}"]) if not pd.isna(latest[f"EMA_{EMA_PERIOD}"]) else close
    rsi = float(latest[f"RSI_{RSI_PERIOD}"]) if not pd.isna(latest[f"RSI_{RSI_PERIOD}"]) else 50.0
    prev_rsi = float(prev[f"RSI_{RSI_PERIOD}"]) if not pd.isna(prev[f"RSI_{RSI_PERIOD}"]) else 50.0

    # Trend filter
    is_above_ema = close > ema
    is_below_ema = close < ema

    # CALL Condition:
    # 1. Price above 200 EMA (Uptrend)
    # 2. RSI oversold or crossing up from oversold (< RSI_OVERSOLD or prev <= RSI_OVERSOLD and rsi > prev)
    if is_above_ema and (rsi <= RSI_OVERSOLD or (prev_rsi <= RSI_OVERSOLD and rsi > RSI_OVERSOLD)):
        return "CALL", f"Price ({close:.5f}) > 200 EMA ({ema:.5f}) & RSI ({rsi:.2f}) Oversold Rebound", close, ema, rsi

    # PUT Condition:
    # 1. Price below 200 EMA (Downtrend)
    # 2. RSI overbought or crossing down from overbought (> RSI_OVERBOUGHT or prev >= RSI_OVERBOUGHT and rsi < prev)
    if is_below_ema and (rsi >= RSI_OVERBOUGHT or (prev_rsi >= RSI_OVERBOUGHT and rsi < RSI_OVERBOUGHT)):
        return "PUT", f"Price ({close:.5f}) < 200 EMA ({ema:.5f}) & RSI ({rsi:.2f}) Overbought Reversal", close, ema, rsi

    trend = "Uptrend" if is_above_ema else "Downtrend"
    return "NEUTRAL", f"{trend} (Close: {close:.5f}, EMA200: {ema:.5f}, RSI14: {rsi:.2f})", close, ema, rsi


def display_status_table(symbol: str, source: str, df: pd.DataFrame, signal: str, reason: str):
    """Renders a formatted rich table with the latest market state for a symbol."""
    table = Table(title=f"Live Market Feed - {symbol} (1-Min | Source: {source})", border_style="cyan")
    table.add_column("Time", justify="center", style="cyan", min_width=8)
    table.add_column("Open", justify="right", min_width=8)
    table.add_column("High", justify="right", style="green", min_width=8)
    table.add_column("Low", justify="right", style="red", min_width=8)
    table.add_column("Close", justify="right", style="bold", min_width=8)
    table.add_column(f"EMA ({EMA_PERIOD})", justify="right", style="magenta", min_width=9)
    table.add_column(f"RSI ({RSI_PERIOD})", justify="right", style="yellow", min_width=7)
    table.add_column("Signal", justify="center", style="bold", min_width=7)

    # Display the last 5 rows for immediate context
    display_rows = df.tail(5)
    for idx, row in display_rows.iterrows():
        t_val = row.get("time")
        if isinstance(t_val, (pd.Timestamp, datetime)):
            t_str = t_val.strftime("%H:%M:%S")
        else:
            t_str = str(t_val)[:19].split(" ")[-1] if t_val is not None else "-"

        is_last = (idx == df.index[-1])
        row_signal = signal if is_last else "-"
        signal_style = "bold green" if row_signal == "CALL" else ("bold red" if row_signal == "PUT" else "white")

        table.add_row(
            t_str,
            f"{float(row['open']):.5f}",
            f"{float(row['high']):.5f}",
            f"{float(row['low']):.5f}",
            f"{float(row['close']):.5f}",
            f"{float(row[f'EMA_{EMA_PERIOD}']):.5f}" if not pd.isna(row[f'EMA_{EMA_PERIOD}']) else "N/A",
            f"{float(row[f'RSI_{RSI_PERIOD}']):.2f}" if not pd.isna(row[f'RSI_{RSI_PERIOD}']) else "N/A",
            Text(row_signal, style=signal_style)
        )

    console.print(table)

    if signal == "CALL":
        console.print(Panel(f"[bold green]🚀 ALERT: CALL (BUY) SIGNAL FOR {symbol}[/bold green]\n{reason}\n[bold white]Action: Execute CALL on Quotex for 1-Minute expiration[/bold white]", style="green", border_style="green"))
    elif signal == "PUT":
        console.print(Panel(f"[bold red]🔻 ALERT: PUT (SELL) SIGNAL FOR {symbol}[/bold red]\n{reason}\n[bold white]Action: Execute PUT on Quotex for 1-Minute expiration[/bold white]", style="red", border_style="red"))
    else:
        console.print(f"[dim]Status for {symbol}: {reason}[/dim]\n")


async def run_bot():
    """Main asynchronous routine streaming live candles and generating signals."""
    console.print(Panel(
        f"[bold cyan]Quotex Signal Engine (Live TradingView Stream)[/bold cyan]\n"
        f"[green]Assets Monitored: {', '.join(ASSET_LIST)}[/green]\n"
        f"[dim]Indicators: EMA ({EMA_PERIOD}) | RSI ({RSI_PERIOD}) | Timeframe: 1-Minute[/dim]\n"
        f"[dim]Mode: Direct Market Streaming (Quotex Login Bypassed)[/dim]",
        border_style="cyan"
    ))

    try:
        while True:
            cycle_time = datetime.now().strftime("%H:%M:%S")
            console.print(f"[bold cyan]--- Cycle Scan at {cycle_time} ---[/bold cyan]")

            for symbol in ASSET_LIST:
                df, source = get_live_candles(symbol)
                if df.empty or len(df) < 5:
                    console.print(f"[yellow]⚠️ Could not fetch candle data for {symbol}. Retrying next cycle...[/yellow]")
                    continue

                df = calculate_indicators(df)
                signal, reason, close, ema, rsi = check_trading_signal(df)
                display_status_table(symbol, source, df, signal, reason)

            await asyncio.sleep(POLL_INTERVAL)

    except (KeyboardInterrupt, asyncio.CancelledError):
        console.print("\n[yellow]Stopping signal engine...[/yellow]")
    finally:
        console.print("[green]Signal engine stopped cleanly.[/green]")


if __name__ == "__main__":
    try:
        asyncio.run(run_bot())
    except KeyboardInterrupt:
        console.print("\n[yellow]Exited.[/yellow]")
